version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*forge*"
      - dependency-name: "*neoforge*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
      - dependency-name: "*lazydfu*"
  - package-ecosystem: gradle
    directory: '/1.18.2'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
      - dependency-name: "*lazydfu*"
  - package-ecosystem: gradle
    directory: '/1.18.2-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
      - dependency-name: "*lazydfu*"
  - package-ecosystem: gradle
    directory: '/1.18.2-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
      - dependency-name: "*lazydfu*"
  - package-ecosystem: gradle
    directory: '/1.18.2-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
      - dependency-name: "*lazydfu*"
  - package-ecosystem: gradle
    directory: '/1.19.2'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.2-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.2-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.2-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.4'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.4-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.4-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.19.4-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.1'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.1-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.1-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.1-neoforge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*neoforge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.1-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.2'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.2-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.2-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.2-neoforge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*neoforge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.2-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.4'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.4-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.4-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.4-neoforge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*neoforge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.4-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*quilted-fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.6'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
  - package-ecosystem: gradle
    directory: '/1.20.6-forge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*forge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.6-fabric'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.6-neoforge'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*neoforge*"
      - dependency-name: "*architectury.loom*"
  - package-ecosystem: gradle
    directory: '/1.20.6-quilt'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric-api*"
      - dependency-name: "*modmenu*"
      - dependency-name: "*architectury.loom*"
