version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*minecraft*"
      - dependency-name: "*fabric*"
      - dependency-name: "*quilt*"
      - dependency-name: "*forge*"
