variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/InGameAccountSwitcher-Forge-1.9.4-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/InGameAccountSwitcher-Forge-1.9.4-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
    
deploy:
  stage: deploy
  script:
  - ./gradlew clean build uploadArchives curseforge uploadToModsIO -PsecretSalt=$secretSalt -PcurseForgeApiKey=$curseForgeApiKey -PmodsioApiKey=$modsioApiKey
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "InGameAccountSwitcher-Forge-1.9.4-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
